name: My First Workflow

on: push

jobs:
    firs_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message
              run: echo "My first GitHub Actions Job/Step"
            - name: List files
              run: ls
            - name: Read file
              run: cat README.md
              
